@----------------------------------------------------------
@ Labo ARO2 - Micro architecture DECODE
@ HEIG-VD / Institut REDS
@ Prof. C. Andrés Pena, R. Mosqueron
@ Ass. Flavio Capitao, Anthony Convers, 
@      Alexandre Malki, Gaetan Matthey
@----------------------------------------------------------
@	Auteur	:	
@	Date	:
@----------------------------------------------------------
@
@	Description de votre programme
@
@----------------------------------------------------------

mov r0, #3
mov r2, r0
add r3, r2, #7
add r5, r3, r0
and r3, r5
lsl r1, r5, #2
sub r0, r3, r1
